modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Cyborgmas/VillagerServices/issues"
[[mods]]
modId="villagerservices"
version="${file.jarVersion}"
displayName="Villager Services"
displayURL="https://www.curseforge.com/minecraft/mc-mods/villager-services"
logoFile="logo.png"
authors="Cyborgmas"
description='''
Adds an API to add trades that provide services instead of items.
'''
[[dependencies.villagerservices]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.villagerservices]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
